import { IsIn, IsOptional, IsString, IsUUID, Length, Matches } from 'class-validator';

/** The one shape a password may have: six letters or digits. */
const PASSWORD_PATTERN = /^[A-Za-z0-9]{6}$/;
const PASSWORD_MESSAGE = 'password must be exactly 6 letters or digits';

/**
 * `POST /auth/login`.
 *
 * The phone is validated to E.164 shape here so a malformed number never
 * reaches the throttle — otherwise a caller could spend someone else's
 * budget by varying the formatting of their number.
 */
export class LoginDto {
  @IsString()
  @Matches(/^\+[1-9]\d{7,14}$/, {
    message: 'phone must be in E.164 format, e.g. +2126XXXXXXXX',
  })
  phone: string;

  @IsString()
  @Matches(PASSWORD_PATTERN, { message: PASSWORD_MESSAGE })
  password: string;

  /**
   * Per-install identifier the refresh token is scoped to (`ACC-07`).
   *
   * Generated by the client, deliberately random rather than a hardware id —
   * a hardware id would be device fingerprinting.
   */
  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;
}

/** `PATCH /auth/me/password`. */
export class ChangePasswordDto {
  @IsString()
  @Matches(PASSWORD_PATTERN, { message: PASSWORD_MESSAGE })
  current_password: string;

  @IsString()
  @Matches(PASSWORD_PATTERN, { message: PASSWORD_MESSAGE })
  new_password: string;
}

/** `POST /auth/refresh`. */
export class RefreshDto {
  @IsString()
  @Length(16, 512)
  refresh_token: string;

  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;
}

/** `PATCH /auth/me/availability` — "HH:MM" bounds in the organisation's zone. */
export class AvailabilityDto {
  @Matches(/^([01]\d|2[0-3]):[0-5]\d$/)
  start: string;

  @Matches(/^([01]\d|2[0-3]):[0-5]\d$/)
  end: string;
}

/** `POST /auth/devices` — registers or updates the FCM token. */
export class RegisterDeviceDto {
  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;

  @IsOptional()
  @IsString()
  push_token?: string;

  @IsOptional()
  @IsIn(['ios', 'android', 'web'])
  platform?: 'ios' | 'android' | 'web';
}
