import { IsIn, IsOptional, IsString, IsUUID, Length, Matches } from 'class-validator';

/**
 * `POST /auth/otp/request`.
 *
 * The phone is validated to E.164 shape here so a malformed number never
 * reaches the rate limiter — otherwise a caller could spend someone else's
 * budget by varying the formatting of their number.
 */
export class RequestOtpDto {
  @IsString()
  @Matches(/^\+[1-9]\d{7,14}$/, {
    message: 'phone must be in E.164 format, e.g. +2126XXXXXXXX',
  })
  phone: string;
}

/** `POST /auth/otp/verify`. */
export class VerifyOtpDto {
  @IsString()
  @Matches(/^\+[1-9]\d{7,14}$/)
  phone: string;

  @IsString()
  @Length(6, 6)
  @Matches(/^\d{6}$/)
  code: string;

  /**
   * Per-install identifier the refresh token is scoped to (`ACC-07`).
   *
   * Generated by the client, deliberately random rather than a hardware id —
   * a hardware id would be device fingerprinting.
   */
  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;
}

/** `POST /auth/refresh`. */
export class RefreshDto {
  @IsString()
  @Length(16, 512)
  refresh_token: string;

  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;
}

/** `POST /auth/devices` — registers or updates the FCM token. */
export class RegisterDeviceDto {
  // A uuid, because `user_device.id` is one. Validating the shape here turns
  // a malformed id into a 422 the client can act on rather than a 500 from the
  // database driver.
  @IsUUID()
  device_id: string;

  @IsOptional()
  @IsString()
  push_token?: string;

  @IsOptional()
  @IsIn(['ios', 'android', 'web'])
  platform?: 'ios' | 'android' | 'web';
}
